image: gcc

build:
  stage: build
  before_script:
    - apt update && apt -y install make cmake autoconf
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - mybinary

test:
  stage: test
  script:
    - chmod +x test/runAllTests.sh
    - test/runAllTests.sh

documentation:
  stage: documentation
  script:
    - apt update
    - apt -y install doxygen
    - apt -y install graphviz
    - apt -y install pdflatex
    - apt -y install make
    - ./docs/generateDocumentation.sh
  artifacts:
    paths:
      - docs