image: gcc

stages:
  - build
  - test
  - documentation

before_script:
  - apt update

build:
  stage: build
  script:
    - apt -y install make cmake autoconf
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - mybinary

test:
  stage: test
  script:
    - apt -y install jq
    - cmake . -B ./cmake-build-debug
    - cd cmake-build-debug
    - cmake --build .
    - cd ..
    - chmod +x ./test/runAllTests.sh
    - chmod +x ./test/runOneTest.sh
    - ./test/runAllTests.sh

documentation:
  stage: documentation
  script:
    - apt -y install doxygen
    - apt -y install graphviz
    - apt -y install pdflatex
    - apt -y install make
    - ./docs/generateDocumentation.sh
  artifacts:
    paths:
      - docs